### PR TITLE
test labeled PR

### PR DESCRIPTION
**Pull request by yi-Xu-0100**

### CODE REVIEW

**Comment by vivaxy** [comment]
@yi-Xu-0100 Hi, what's labeled PR for?

P.S. I think `bate` should be `beta`.

**Comment by yi-Xu-0100** [comment]
@vivaxy This is a test for a PR when the label of `wait-to-build` created. The build action will create a test extension as the artifact. 😀

https://github.com/vivaxy/vscode-conventional-commits/blob/e5779bb3e838ca96ebb313b102877645f6fc3b5e/.github/workflows/build.yml#L12-L25

https://github.com/vivaxy/vscode-conventional-commits/actions/runs/653717074

**Comment by vivaxy** [comment]
@yi-Xu-0100 Is it for beta tests? When will we use the labeled PR workflow? 😀

**Comment by yi-Xu-0100** [comment]
@vivaxy Now the build action can trigger the push event for master branch, the manually building event, and the building event for labeled PR. If the build is necessary for the PR, we can label the PR to build a test extension. The `vsix` can be installed in VS Code for the test. 

The build for PR should after checking the changes of codes, for maintaining the security of the automation building. 

See security blog of GitHub: <https://securitylab.github.com/research/github-actions-preventing-pwn-requests>

**Comment by yi-Xu-0100** [comment]
The `bate` is a spelling mistake, I will fix it as `beta` next time. Thanks to point it out. 😀

**Comment by vivaxy** [comment]
@yi-Xu-0100 Thanks for explaining clearly. 👍

**Pull request closed without merging**
