### PR TITLE
fix(commitlint): :bug: repair commitlint configuration failures

### LINKED ISSUE #102: [BUG] Extenstion stopped recognizing commitlint rules
**Describe the bug**
Since yesterday the extension stopped recognizing configured scopes and other settings for me and my colleagues. Unfortunately I have no idea why, nothing has changed about the setup of the repository or the configurations themselves. Have there been any recent changes to the extensions which may have caused it? The last working version for us seems to be `1.16.1`.

**Application logs**
```
Activated
vscode.env.language: en
[warning] getNLS: Missing translation for en
Started
VSCode version: 1.54.3
VSCode Conventional Commits version: 1.18.0
Git version: 1.0.0
autoCommit: true
gitmoji: false
emojiFormat: code
scopes: 
lineBreak: 
promptScopes: true
git.enableSmartCommit: true
git.smartCommitChanges: all
git.postCommitCommand: none
arg: undefined
git.repositories: /home/redacted
workspaceFolders: /home/redacted
commitlintRuleConfigs: {}
```

### PR DESCRIPTION
**Pull request by yi-Xu-0100**
After webpack, it needs fix the `require` expression when require dynamic resources.

close #102

### CODE REVIEW

**Comment by vivaxy** [comment]
Are we rewriting `@commitlint/load`, `resolve-extends`, `import-fresh` and `resolve-global`?
It there another robust way to do it? What if there is another module with `require` installed?
Can we make change to webpack to fix this?

**Comment by yi-Xu-0100** [comment]
@vivaxy In the most time, The `require` will lead the webpack to bundle the JS into extension.js. But sometime, we need to require the dynamic resources, and the webpack will show warning about it. 😀

```log
webpack 5.25.0 compiled with 9 warnings in 6736 ms

** if we make stat.warnings = true in webpack.config.js, the warning will show as follow. **

WARNING in ./node_modules/@commitlint/load/lib/load.js 34:24-53
Critical dependency: the request of a dependency is an expression
 @ ./src/lib/commitlint.ts 16:15-42
 @ ./src/lib/conventional-commits.ts 21:21-44
 @ ./src/extension.ts 9:31-68

WARNING in ./node_modules/@commitlint/load/lib/utils/load-plugin.js 22:21-38
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@commitlint/load/lib/load.js 14:38-68
 @ ./src/lib/commitlint.ts 16:15-42
 @ ./src/lib/conventional-commits.ts 21:21-44
 @ ./src/extension.ts 9:31-68

WARNING in ./node_modules/@commitlint/load/lib/utils/load-plugin.js 27:16-41
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@commitlint/load/lib/load.js 14:38-68
 @ ./src/lib/commitlint.ts 16:15-42
 @ ./src/lib/conventional-commits.ts 21:21-44
 @ ./src/extension.ts 9:31-68

WARNING in ./node_modules/@commitlint/load/lib/utils/load-plugin.js 42:33-58
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@commitlint/load/lib/load.js 14:38-68
 @ ./src/lib/commitlint.ts 16:15-42
 @ ./src/lib/conventional-commits.ts 21:21-44
 @ ./src/extension.ts 9:31-68

WARNING in ./node_modules/@commitlint/resolve-extends/lib/index.js 40:40-47
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@commitlint/load/lib/load.js 13:42-80
 @ ./src/lib/commitlint.ts 16:15-42
 @ ./src/lib/conventional-commits.ts 21:21-44
 @ ./src/extension.ts 9:31-68

WARNING in ./node_modules/@commitlint/resolve-extends/lib/index.js 55:28-57
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@commitlint/load/lib/load.js 13:42-80
 @ ./src/lib/commitlint.ts 16:15-42
 @ ./src/lib/conventional-commits.ts 21:21-44
 @ ./src/extension.ts 9:31-68

WARNING in ./node_modules/import-fresh/index.js 31:31-48
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@commitlint/resolve-extends/lib/index.js 22:20-43
 @ ./node_modules/@commitlint/load/lib/load.js 13:42-80
 @ ./src/lib/commitlint.ts 16:15-42
 @ ./src/lib/conventional-commits.ts 21:21-44
 @ ./src/extension.ts 9:31-68

WARNING in ./node_modules/resolve-global/index.js 7:9-71
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@commitlint/resolve-extends/lib/index.js 18:0-25
 @ ./node_modules/@commitlint/load/lib/load.js 13:42-80
 @ ./src/lib/commitlint.ts 16:15-42
 @ ./src/lib/conventional-commits.ts 21:21-44
 @ ./src/extension.ts 9:31-68

WARNING in ./node_modules/resolve-global/index.js 9:9-70
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@commitlint/resolve-extends/lib/index.js 18:0-25
 @ ./node_modules/@commitlint/load/lib/load.js 13:42-80
 @ ./src/lib/commitlint.ts 16:15-42
 @ ./src/lib/conventional-commits.ts 21:21-44
 @ ./src/extension.ts 9:31-68

```

Before this version, when we make a build it will occur 9 warning and I do not know the solution and what will cause. I try to figure out the information about `Critical dependency`, the solution is to make it silent, and I do it also. 😥

After the thinking, the people marked the warning as silent because they have fully knowledge about the result. So I delete the `stat.warning` and will fix every warning next time. 😀

I think the most time we do not need the dynamic resources from the environment. So it is not be worried about every `require` expression.

I did not find the more elegant way to fix the issue. It can be upgrade if there are any suggestions. 😊

**Comment by vivaxy** [comment]
@yi-Xu-0100 Thank you for your explanation.

Is it possible to mark the `Critical dependency: the request of a dependency is an expression` as an error, so we can notice the problem while building.

**Comment by yi-Xu-0100** [comment]
@vivaxy If you test the beta version with `commitlint` and it works well, I think we should make it as a patch as soon as possible. 😀

If I found the better way to upgrade it, I will try to make a PR. 😜

**Review by vivaxy — APPROVED** [review]

**Comment by yi-Xu-0100** [comment]
@vivaxy I find a plugin of webpack to change warnings to errors. 🤪

I think the warning also can solve by the webpack plugin, but I didn't find it. 😅

I find a similar **[`post`](https://zhuanlan.zhihu.com/p/52990313)** about it. But the code is old for the webpack 5. And the corresponding codes has been deleted in the latest version. 😥

**Comment by vivaxy** [comment]
> @vivaxy I find a plugin of webpack to change warnings to errors. 🤪
> 
> I think the warning also can solve by the webpack plugin, but I didn't find it. 😅
> 
> I find a similar **[`post`](https://zhuanlan.zhihu.com/p/52990313)** about it. But the code is old for the webpack 5. And the corresponding codes has been deleted in the latest version. 😥

Add more refs:
- https://github.com/webpack/webpack/pull/11316
- https://github.com/webpack/webpack/issues/198#issuecomment-104688430

**Pull request merged**
